<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class Wards extends Seeder
{
	public function run()
	{
		$wards_data = [
			['ward_name' => 'Kaselya', 'ward_slug' => 'kaselya', 'ward_district' => 1, 'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Kidaru', 'ward_slug' => 'kidaru', 'ward_district' => 1, 'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Kinampanda ', 'ward_slug' => 'kinampanda ', 'ward_district' => 1, 'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Kiomboi', 'ward_slug' => 'kiomboi', 'ward_district' => 1, 'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Kisiriri ', 'ward_slug' => 'kisiriri ', 'ward_district' => 1, 'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Kyengege', 'ward_slug' => 'kyengege', 'ward_district' => 1, 'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Maluga', 'ward_slug' => 'maluga', 'ward_district' => 1, 'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mbelekese', 'ward_slug' => 'mbelekese', 'ward_district' => 1, 'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mgongo', 'ward_slug' => 'mgongo', 'ward_district' => 1, 'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mtekente', 'ward_slug' => 'mtekente', 'ward_district' => 1, 'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mtoa', 'ward_slug' => 'mtoa', 'ward_district' => 1, 'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mukulu', 'ward_slug' => 'mukulu', 'ward_district' => 1, 'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Ndago', 'ward_slug' => 'ndago', 'ward_district' => 1, 'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Ndulungu', 'ward_slug' => 'ndulungu', 'ward_district' => 1, 'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Ntwike', 'ward_slug' => 'ntwike', 'ward_district' => 1, 'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Old Kiomboi', 'ward_slug' => 'old-kiomboi', 'ward_district' => 1, 'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Shelui', 'ward_slug' => 'shelui', 'ward_district' => 1, 'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Tulya', 'ward_slug' => 'tulya', 'ward_district' => 1, 'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Ulemo', 'ward_slug' => 'ulemo', 'ward_district' => 1, 'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Urughu', 'ward_slug' => 'Urughu', 'ward_district' => 1, 'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			
			['ward_name' => 'Chikola', 'ward_slug' => 'chikola', 'ward_district' => 2,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Chikuyu', 'ward_slug' => 'Chikuyu', 'ward_district' => 2,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Heka ', 'ward_slug' => 'heka ', 'ward_district' => 2,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Isseke', 'ward_slug' => 'isseke', 'ward_district' => 2,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Kintinku ', 'ward_slug' => 'kintinku ', 'ward_district' => 2,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Majiri', 'ward_slug' => 'majiri', 'ward_district' => 2,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Makanda', 'ward_slug' => 'makanda', 'ward_district' => 2,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Makuru', 'ward_slug' => 'makuru', 'ward_district' => 2,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Makutopora', 'ward_slug' => 'makutopora', 'ward_district' => 2,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Manyoni', 'ward_slug' => 'manyoni', 'ward_district' => 2,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Maweni', 'ward_slug' => 'maweni', 'ward_district' => 2,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mkwewse', 'ward_slug' => 'mkwewse', 'ward_district' => 2,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Muhalala', 'ward_slug' => 'muhalala', 'ward_district' => 2,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Nkonko', 'ward_slug' => 'nkonko', 'ward_district' => 2,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Sanza', 'ward_slug' => 'sanza', 'ward_district' => 2,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Saranda', 'ward_slug' => 'saranda', 'ward_district' => 2,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Sasajila', 'ward_slug' => 'sasajila', 'ward_district' => 2,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Sasilo', 'ward_slug' => 'sasilo', 'ward_district' => 2,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Solya', 'ward_slug' => 'solya', 'ward_district' => 2,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			
			['ward_name' => 'Ikhanoda', 'ward_slug' => 'ikhanda', 'ward_district' => 3,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Ilongero', 'ward_slug' => 'ilongero', 'ward_district' => 3,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Itaja', 'ward_slug' => 'itaja ', 'ward_district' => 3,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Kijota', 'ward_slug' => 'kijota', 'ward_district' => 3,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Kinyagigi ', 'ward_slug' => 'kinyagigi ', 'ward_district' => 3,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Kinyeto', 'ward_slug' => 'kinyeto', 'ward_district' => 3,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Maghojoa', 'ward_slug' => 'maghojoa', 'ward_district' => 3,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Makuro', 'ward_slug' => 'makuro', 'ward_district' => 3,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Merya ', 'ward_slug' => 'merya', 'ward_district' => 3,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mgori', 'ward_slug' => 'mgori', 'ward_district' => 3,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mrama', 'ward_slug' => 'mrama', 'ward_district' => 3,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Msange ', 'ward_slug' => 'msange', 'ward_district' => 3,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Msisi', 'ward_slug' => 'msisi', 'ward_district' => 3,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mtinko', 'ward_slug' => 'mtinko', 'ward_district' => 3,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mudida', 'ward_slug' => 'mudida', 'ward_district' => 3,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mughamo', 'ward_slug' => 'mughamo', 'ward_district' => 3,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mughunga', 'ward_slug' => 'mughunga', 'ward_district' => 3,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mwasauya', 'ward_slug' => 'mwasauya', 'ward_district' => 3,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Ngimu', 'ward_slug' => 'ngimu', 'ward_district' => 3,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Ntonge', 'ward_slug' => 'ntonge', 'ward_district' => 3,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Ughandi', 'ward_slug' => 'ughandi', 'ward_district' => 3,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			
			['ward_name' => 'Ipembe', 'ward_slug' => 'ipembe', 'ward_district' => 4,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Kindai', 'ward_slug' => 'kindai', 'ward_district' => 4,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Kisaki', 'ward_slug' => 'kisaki ', 'ward_district' => 4,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Majengo', 'ward_slug' => 'majengo', 'ward_district' => 4,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mandewa ', 'ward_slug' => 'mandewa ', 'ward_district' => 4,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Minga', 'ward_slug' => 'minga', 'ward_district' => 4,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Misuna', 'ward_slug' => 'misuna', 'ward_district' => 4,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mitunduruni', 'ward_slug' => 'mitunduruni', 'ward_district' => 4,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mtamaa', 'ward_slug' => 'mtamaa', 'ward_district' => 4,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mtipa', 'ward_slug' => 'mtipa', 'ward_district' => 4,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mughanga', 'ward_slug' => 'mughanga', 'ward_district' => 4,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mungumaji', 'ward_slug' => 'mungumaji', 'ward_district' => 4,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mwankoko', 'ward_slug' => 'mwankoko', 'ward_district' => 4,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Uhamaka', 'ward_slug' => 'uhamaka', 'ward_district' => 4,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Unyambwa', 'ward_slug' => 'unyambwa', 'ward_district' => 4,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Unyamikumbi', 'ward_slug' => 'unyamikumbi', 'ward_district' => 4,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Unyianga', 'ward_slug' => 'unyiaga', 'ward_district' => 4,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Utemini', 'ward_slug' => 'utemini', 'ward_district' => 4,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			
			['ward_name' => 'Dung\'unyi', 'ward_slug' => 'dung\'unyi', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Ighombwe', 'ward_slug' => 'ighombwe', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Iglansoni', 'ward_slug' => 'iglansoni ', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Ihanja', 'ward_slug' => 'ihanja', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Ikungi ', 'ward_slug' => 'ikungi ', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Irisya', 'ward_slug' => 'irisya', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Iseke', 'ward_slug' => 'iseke', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Issuna', 'ward_slug' => 'issuna', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Iyumbu', 'ward_slug' => 'iyumbu', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Kikio', 'ward_slug' => 'kikio', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Kituntu', 'ward_slug' => 'kituntu', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Lighwa', 'ward_slug' => 'lighwa', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Makilawa', 'ward_slug' => 'makilawa', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Makiungu', 'ward_slug' => 'makiungu', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mang\'onyi', 'ward_slug' => 'mang\'onyi', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mgungira', 'ward_slug' => 'mgungira', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Minyughe', 'ward_slug' => 'minyughe', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Misughaa', 'ward_slug' => 'misughaa', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mkiwa', 'ward_slug' => 'mkiwa', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mtunduru', 'ward_slug' => 'mtunduru', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Muhintiri', 'ward_slug' => 'muhintiri', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mungaa', 'ward_slug' => 'mungaa', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mwaru', 'ward_slug' => 'mwaru', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Ntuntu', 'ward_slug' => 'ntuntu', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Puma', 'ward_slug' => 'puma', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Sambaru', 'ward_slug' => 'sambaru', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Sepuka', 'ward_slug' => 'sepuka', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Siuyu', 'ward_slug' => 'siuyu', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Unyahati', 'ward_slug' => 'unyahati', 'ward_district' => 5,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			
			['ward_name' => 'Gumanga', 'ward_slug' => 'gumanga', 'ward_district' => 6,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Ibaga', 'ward_slug' => 'ibaga', 'ward_district' => 6,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Iguguno', 'ward_slug' => 'iguguno', 'ward_district' => 6,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Ilunda', 'ward_slug' => 'ilunda', 'ward_district' => 6,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Kikhonda', 'ward_slug' => 'kikhonda', 'ward_district' => 6,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Kinampundu', 'ward_slug' => 'kinampundu', 'ward_district' => 6,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Kinyangiri', 'ward_slug' => 'kinyangiri', 'ward_district' => 6,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Matongo', 'ward_slug' => 'matongo', 'ward_district' => 6,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Miganga', 'ward_slug' => 'miganga', 'ward_district' => 6,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mpambala', 'ward_slug' => 'mpambala', 'ward_district' => 6,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Msingi', 'ward_slug' => 'msingi', 'ward_district' => 6,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mwanga', 'ward_slug' => 'mwanga', 'ward_district' => 6,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Mwangeza', 'ward_slug' => 'mwangeza', 'ward_district' => 6,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Nduguti', 'ward_slug' => 'nduguti', 'ward_district' => 6,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Nkalakala', 'ward_slug' => 'nkalala', 'ward_district' => 6,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Nkinto', 'ward_slug' => 'nkinto', 'ward_district' => 6,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
			['ward_name' => 'Tumuli', 'ward_slug' => 'tumuli', 'ward_district' => 6,'ward_longtude' => '-6.8986', 'ward_latitude' => '36.564'],
		];
		
		foreach($wards_data as $data)
		{
			$this->db->table('wards')->insert($data);
		}
	}
}